## Endpoint Toursight API ##

# VIEW ALL USERS
GET http://localhost:5000/api/users
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoidXNlcjIiLCJlbWFpbCI6InVzZXIyQGdtYWlsLmNvbSIsImlhdCI6MTY1MjYyMzEwNywiZXhwIjoxNjUyNjIzMTY3fQ.kCnb2kgvxp-JqFYdpPA_NkfQ2DSuxOnih3fAm8KkYZk
###

# REGISTER
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "username": "user2",
    "email": "user2@gmail.com",
    "password": "12345678"
}
###

# LOGIN 
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "user2@gmail.com",
    "password": "12345678"
}
###

# REFRESH TOKEN
GET http://localhost:5000/api/token
###

# LOGOUT
DELETE http://localhost:5000/api/logout
###

# RESOURCE ALL LANDMARK
GET http://localhost:5000/api/landmark
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoidXNlcjIiLCJlbWFpbCI6InVzZXIyQGdtYWlsLmNvbSIsImlhdCI6MTY1MjY5NDk0MCwiZXhwIjoxNjUyNjk1MDAwfQ.M7unvmVJ1ipp6_ePHHdbNXtiOJmfzbR0ljeain0iN5Q
###

# RESOURCE LANDMARK BY ID
GET http://localhost:5000/api/landmark/1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoidXNlcjIiLCJlbWFpbCI6InVzZXIyQGdtYWlsLmNvbSIsImlhdCI6MTY1MjYzMDAyNywiZXhwIjoxNjUyNjMwMDg3fQ.FMEjjrfQlfzvTh1UXFx2ak3sW-Sib7yYpA3aGp2oBzo
###

# LIHAT GAMBAR CONTOH /images\\namafile.jpg di postman
GET http://localhost:5000/images\\tugujogja.jpg
###
